services:
  cm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ref
    network_mode: host
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      CESAR_USERNAME: ${CESAR_USERNAME}
      CESAR_PASSWORD: ${CESAR_PASSWORD}
      WIALON_TOKEN: ${WIALON_TOKEN}
      WIALON_HOST: ${WIALON_HOST}
      MAIL_MAIL: ${MAIL_MAIL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SALT: ${SALT}
      DEV: ${DEV}
    ports:
      - "31500:31500"
    stdin_open: true
    tty: true
    restart: always
