version: '3.8'

services:
  flask_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    stdin_open: true   # Открывает стандартный вход
    tty: true          # Позволяет использовать терминал
    restart: always