apiVersion: v1
kind: Service
metadata:
  name: flask-cm-spectr-service
  namespace: prd-cm
spec:
  selector:
    app: flask-cm-spectr
  ports:
    - protocol: TCP
      port: 32448
      targetPort: 31500
      nodePort: 32448
  type: NodePort
